# Generated by Django 2.0.7 on 2018-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='pic_folder/None/anonymous.jpg', upload_to='EVOTE/media/pic_folder/election_user'),
        ),
    ]
