# Generated by Django 2.0.7 on 2018-07-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180720_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/root/Desktop/EVOTE/media/pic_folder/None/anonymous.jpg', upload_to='EVOTE/media/pic_folder/election_user'),
        ),
    ]
