# Generated by Django 2.0.7 on 2018-07-21 03:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('profile_photo', models.ImageField(blank=True, default='../media/pic_folder/None/anonymous.jpg', upload_to='../media/pic_folder/candidate_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('election_url', models.SlugField(blank=True, max_length=255)),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'end_time',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_code', models.CharField(blank=True, max_length=15)),
                ('f_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='f_voter',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='election.Voter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='f_election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
        ),
    ]
